name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Job 1: Run Tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: false  # Fail the job if tests fail

  # Job 2: Build and Push Docker Image
  build:
    runs-on: ubuntu-latest
    needs: test  # This job depends on the test job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:${GITHUB_SHA} .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${GITHUB_SHA}
  
  # Job 3: Deploy to Kubernetes
  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Kubernetes Cluster
        run: |
          kubectl config set-cluster k8s-cluster --server=https://<your-cluster-api-endpoint>
          kubectl config set-credentials user --token=${{ secrets.K8S_TOKEN }}
          kubectl config set-context default --cluster=k8s-cluster --user=user
          kubectl config use-context default

      - name: Apply Kubernetes Deployment
        run: |
          kubectl set image deployment/node-app node-app=${{ secrets.DOCKER_USERNAME }}/node-app:${GITHUB_SHA}
          kubectl rollout status deployment/node-app
    
  # Job 4: Send Slack Notification
  notify:
    runs-on: ubuntu-latest
    needs: deploy  # This job depends on the deploy job
    steps:
      - name: Send Notification on Deployment Status
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment Successful!"}' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Failure Notification on Deployment Status
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment Failed!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
            - name: Setup Node.js environment
  uses: actions/setup-node@v4.1.0
  with:
    # Set always-auth in npmrc.
    always-auth: # optional, default is false
    # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
    node-version: # optional
    # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
    node-version-file: # optional
    # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec.
    check-latest: # optional
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.
    registry-url: # optional
    # Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).
    scope: # optional
    # Used to pull node distributions from node-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
    cache: # optional
    # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
    cache-dependency-path: # optional
          
